# -*- coding: utf-8 -*-
"""information_gain.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jS2iJ_hpPiy3tApaMQ9EZz4xJj32hA0S
"""

# Commented out IPython magic to ensure Python compatibility.
from sklearn.feature_selection import mutual_info_classif

import matplotlib.pyplot as plt

# %matplotlib inline

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.losses import sparse_categorical_crossentropy
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import KFold
from numpy import mean
import numpy as np

data = pd.read_csv("/content/drive/MyDrive/Postdoctoral research/Deep learn/SOFA/benchmark/all_patients.csv")

x = data.iloc[:, 6:36].values
y = data.iloc[:, 5].values

importances = mutual_info_classif(x,y)

"""Each input feature will get an importance score attributed. This is saved and treated in R for enhanced data visualization"""

importances